export const remove = async (): Promise<void> => {
  try {
    throw new Error('failed')
  } catch (error) {
    console.log('use service failed!!')
  }
}
